Repository wordpress-mobile/WordPress-Login-Flow-Android, pull requests merged in 2022-11, with the labels that each got.

#103 Update `minSdkVersion` (from `21` to `24`)
  WordPressLoginFlow/build.gradle
  WordPressLoginFlow/src/main/res/values-v23/themes.xml
  WordPressLoginFlow/src/main/res/values/themes.xml
  build.gradle
Labels: enhancement, Tooling

#104 [Build] Remove Fetch Style Plugin
  build.gradle
  settings.gradle
Labels: Tooling, Tech Debt

#105 Use Android AMI in Buildkite
  .buildkite/pipeline.yml
Labels: Tooling
